### ISSUE TITLE
Webhook to upload endpoint

### ISSUE THREAD

**Issue by jotacemarin** [darkzam/FilesManager.API#11]
https://github.com/darkzam/FilesManager.API/blob/60fe9a058a8238293d422acc939809caf649ea15/src/FilesManager.API/Controllers/FilesController.cs#L71-L77

Eyyy you can made a little improvement for this endpoint? I need a webhook to retrieve `FileMetadata` model (avoid `Category` model) from media upload.

**Comment by darkzam** [comment]
Fixed on Feature/implement parameterized settings #12 

Closing Issue...
